spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf-8&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file:
    name: /var/log/blog/blog.log
  level:
    root: warn
    con.lh.myblog: info

server:
  port: 8081
